### ISSUE TITLE
Enable strong mode flags

### ISSUE THREAD

**Issue by ranquild** [dart-league/serializable#2]
Please enable strong mode flags https://www.dartlang.org/guides/language/analysis-options:
```
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```
